#!/bin/bash

read -p "Ссылка: " a

read -p "1 - PH 720p, 2 - PH 1080p: " b

if [[ $b == 1 ]]; then
  
  yt-dlp --no-playlist -f hls-2053 --cookies-from-browser firefox -o "%(title)s.%(ext)s"  --sponsorblock-remove all --merge-output-format mkv $a
  
elif [[ $b == 2 ]]; then
  
  yt-dlp --no-playlist -f hls-3843 --cookies-from-browser firefox -o "%(title)s.%(ext)s"  --sponsorblock-remove all --merge-output-format mkv $a
  
fi
