setopt autocd
autoload -U compinit && compinit
zstyle ':completion:*' menu select
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_ROOT_ICON='\uF09C'
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='196'  #POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='007'   #default
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND='000'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='000'
POWERLEVEL9K_DIR_HOME_FOREGROUND='195'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='195'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='195'
POWERLEVEL9K_DIR_ETC_FOREGROUND='195'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='195'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='195'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='195'
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time)

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

alias 1='yes | yay -Syyu && yes | yay -Scc && yes | yay -Rns $(yay -Qtdq)'
alias 2='sudo reflector --verbose -l 5 -p https --sort rate --save /etc/pacman.d/mirrorlist' # обновить зеркала
alias 3='source ~/.zshrc'            # обновить терминал
alias h='history'
alias yr='yay -Rns --noconfirm'
alias yu='yay -U --mflags --skipinteg --noconfirm'
alias ys='yay -S --mflags --skipinteg --noconfirm'
alias y='yay --mflags --skipinteg --noconfirm'
alias p='yay -Ps'                    # статистика пакетов
alias pacman='sudo pacman --noconfirm'
alias c='clear'
alias ping='ping -c 5 ya.ru'         # пинг
alias ports='netstat -tulanp'        # открытые порты
#alias ls='ls -Alh --color'           # показать скрытые файлы
alias ls='lsd -a'
alias cat='bat'
#fd = find   - поиск
alias du='sudo ncdu --color dark'    # показать размер файлов
alias ..='cd ..'                     # перейти в директорию уровнем выше
alias .='cd -'                       # перейти в директорию, в которой находились до перехода в текущую директорию
alias tree='tree -Cha'               # просмотр дерева директорий
alias grep='grep --color=auto'
alias mkdir='mkdir -p'
alias rm='sudo rm -rf'
alias cp='cp -r'
alias g='git clone'
alias ydl='sh ~/.config/yt-dlp'
alias av="sudo freshclam"            # обновить базы антивируса clamav

echo -ne '\e[1 q'                    # Вид курсора от 1-6
